import {
  ArrowRight,
  ArrowDown,
  Mail,
  Code,
  ExternalLink,
  Home,
  Search,
  Download,
  CheckCircle2,
  Check,
  Send,
  Lock,
  Briefcase,
  User,
  Laptop,
  ChevronDown,
  Loader2,
  MessageCircle,
  Puzzle,
  Star,
  Terminal,
  Award,
  Rocket,
  BadgeCheck,
  Braces,
  Boxes,
  TrendingUp,
  SlidersHorizontal,
  GitCommitHorizontal,
  Handshake,
  Monitor,
  Wrench,
  Cloud,
  FlaskConical,
  Smile,
  Folder,
  Cpu,
  GitBranch,
  Globe,
  MapPin,
  Zap,
  ClipboardCopy,
  XCircle,
  X,
  Menu,
  GraduationCap,
  type LucideIcon,
} from 'lucide-react';
import { cn } from '@/lib/cn';

const icons: Record<string, LucideIcon> = {
  arrow_forward: ArrowRight,
  arrow_downward: ArrowDown,
  mail: Mail,
  code: Code,
  open_in_new: ExternalLink,
  home: Home,
  search: Search,
  download: Download,
  check_circle: CheckCircle2,
  check: Check,
  send: Send,
  lock: Lock,
  briefcase: Briefcase,
  person: User,
  laptop_mac: Laptop,
  expand_more: ChevronDown,
  hourglass_top: Loader2,
  chat_bubble_outline: MessageCircle,
  extension: Puzzle,
  star: Star,
  terminal: Terminal,
  workspace_premium: Award,
  rocket_launch: Rocket,
  verified: BadgeCheck,
  code_blocks: Braces,
  inventory_2: Boxes,
  trending_up: TrendingUp,
  tune: SlidersHorizontal,
  commit: GitCommitHorizontal,
  handshake: Handshake,
  monitor: Monitor,
  build: Wrench,
  cloud: Cloud,
  science: FlaskConical,
  mood: Smile,
  folder_special: Folder,
  developer_board: Cpu,
  alt_route: GitBranch,
  language: Globe,
  location_on: MapPin,
  bolt: Zap,
  content_copy: ClipboardCopy,
  error: XCircle,
  close: X,
  menu: Menu,
  school: GraduationCap,
  work: Briefcase,
};

interface IconProps {
  name: string;
  size?: number;
  className?: string;
}

export default function Icon({ name, size = 24, className = '' }: IconProps) {
  const LucideIcon = icons[name];
  if (!LucideIcon) {
    return null;
  }
  return <LucideIcon size={size} className={cn(className)} />;
}
